export const metadata = {
    title: "RR Technology",
    description: "Generated by create next app",
  };
  
  export default function PublicLayout({ children }) {
    return (
      <>
        {children}
      </>
    );
  }